language: java
jdk:
    oraclejdk8
before_install:
     - rm ~/.m2/settings.xml
     - cp settings.xml ~/.m2
script: mvn clean install deploy
cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    recipients:
      - group.ats.team@axway.com
    on_success: change
    on_failure: always
env:
   global:
     # sonatype username
     - secure: "m6E/UgBR/USfhbG/MWbtQYgDo7gWSTWpv/t5kebH9oA4J8ZysMPXhjrClYp5CRZ1EeGzNlsc2QVrgc3et/ZjB8exYOqZOJ3J85qwfVoreFgX3T8cBsXFmSncM4WgVS1F61obsAuduNTsjwV4QfYEJnRP3/LUq4NZj1XeUBwXN0AX2yiVzymkeEipYRTAp1YZs25PHPqVqtZQvA44DEO8ZXj47zlUsP5FX9cXbzMFghmwTdG4rAJzVabKZMw6PAa785zXYZwExijhOrhYjoDcqf1L+/YqrDv9I/AbbT3Yh5Wm64Naihxi3XYdK6xw7ZbU8PpMzrei567P8TN+yQ8sRHAnpEJ3Z6i8T+u7VDS3MoeQtQRgwVo6uEI++3dPHdBxCJU68Z713a2DHFCX6gDmSrNDmVrNDalkuuzoibmXP2rA7RHG4TNZNK4mFSiObhlHVIBqSML3bcAAKuW/Va4e3Vi/ehz5PpNgU8POW7fSfyI7CpeqsagC/01KZjOmZ5XEZJhsBTFVbg2axBjrXv6/MTu9dcjIpJ05NjDEJOVnITnqBuPAy212t5t5DzazfMgsw/j6qkqsveWZCgrbb2fdzGW5qi324WHwBkOUK+Ca9p28e2olU3Kq8w0ZSf89ldLBEGUMasidQWbQJv6ywSV65Z1iUrwEThInJffaxnGkCwQ="
     # sonatype password
     - secure: "W2VDQOuEJVEAFOfG+8QFQ4+4cWxISG6/N5jsILWSNqayUtWz72VT79Ab0J259pJr5OQGdxtNkV58NWXdfk55vRv9x4asfm2ksVp81ghQ/r07erMKVS9g6EviVNuvS45mZt2qvbY0hg1k/gEGjbQxaaqjeblOH7I2FPshTNykjpRGInUTHB1C+xS1jiwD1a/u7ILuccv02ox/KBh4JUCak6pI4Jlyp2ApziT/TFivWyl9AI4z23Pd1lOhN7AxTgcszXOQ1cjr2OcBvlFbwBPMlfaYdKxMi6cD85QAWA1ARMKWVqGA5oAKKm6inoWC+AKVwaGWhtbqOP8MTKwahJej/HNSF4f01EN9GuthkKYGw7qQ5OZgsAcyGrTbLeZ+Sl4mGyWT8YOPPqwtzloDInzlpt6Gf0qBY94oWG3wndc1qfaQ6RApSoHzFbBXexgnmVK7SQ2NZPptJlwACRJWRnJK1prrc0uwE1JShlD4YrRGIFCI9GyUcPFMSkD/S/3gmPgn1SXgFxCM7jYwVeVDVHF4fvXXdNUjKd060BoVTnTGH5H8OYTFcWHDHxze6rtb2nOU4GXoeJF73DOfOmpS9eIA/pr4/o1bxvYLphEsIM1dndTDorDHfQtqz2e3spvPWo6QpUOKj0exaoLeIdxOIy9FLufPLo79kABZZcFJ5iSnicE="

